/-
Copyright (c) 2026 Zhu Zekai. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zhu Zekai
-/
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Probability.Independence.Basic
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.Data.ENNReal.Real

/-!
# Lovász Local Lemma

This file formalizes the Lovász local lemma: bad events on a probability space that satisfy a
dependency-graph hypothesis and a smallness condition can all be avoided with positive
probability. Both the asymmetric form (per-event weights) and the classical symmetric forms are
covered.

## Main definitions

* `bset`: the event that none of the bad events indexed by a finset occurs.
* `IsDependencyGraph`: the avoidance-event formulation of the dependency-graph hypothesis —
  `A i` is independent of `bset A S`
  for every index set `S` of non-neighbors of `i` (not containing `i`).
* `IsDependencyGraphStrong`: the generated-σ-algebra formulation (global form) — for every
  index `i`, `A i` is independent of the σ-algebra generated by all non-neighbor events `A j`
  (`j ≠ i`, `¬ G.Adj i j`); equivalent to `IsDependencyGraph` (see `isDependencyGraph_iff_strong`
  below).

## Main results

* `lovaszLocalLemma`: the asymmetric Lovász local lemma (ENNReal form):
  if `μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j))` for all `i`, then
  `ENNReal.ofReal (∏ i, (1 - x i)) ≤ μ (⋂ i, (A i)ᶜ)`.
* `lovaszLocalLemma_pos`: the existence form — with positive probability, none of the bad events
  occurs.
* `lovaszLocalLemma_probReal`: the ℝ-valued corollary via `μ.real`.
* `lovaszLocalLemma_exists`: some outcome avoids every bad event.
* `lovaszLocalLemma_symmetric_optimalWeight`: symmetric form with the optimal uniform-weight
  condition
  `(d+1)^(d+1) · p ≤ d^d`.
* `lovaszLocalLemma_symmetric`: the classical symmetric form `e·p·(d+1) ≤ 1`.
* `lovaszLocalLemma_4pd`: the `4·p·d ≤ 1` criterion.
* `lovaszLocalLemma_bset_pos` / `lovaszLocalLemma_cond`: positivity of `bset` events and the
  conditional-probability form of the key lemma.
* `IsDependencyGraph.of_strong` / `IsDependencyGraph.strong` / `isDependencyGraph_iff_strong`:
  the bridge between the avoidance-event and generated-σ-algebra formulations of the
  dependency-graph hypothesis.
* Supporting API: `measure_bset_insert` (peeling identity), `measure_bset_insert_le` (one-step
  peeling bound), `prob_bset_inter_prod` (chain-rule-free product lower bound), `lll_prob_bset`
  (the (P1)+(P2) strong induction — the heart of the proof), and the `cond` glue lemmas
  `cond_eq_of_indepSet`, `cond_compl_eq_one_sub`, `cond_le_one`.

## References

We follow [alonSpencer2016] and [edmondsPaulson2024] for the proof of the Lovász local lemma;
see [erdosLovasz1975] for the original result.
-/

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal

namespace TCSLean.LovaszLocal

variable {Ω ι : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
  [Fintype ι] [DecidableEq ι]

/-- For a family of bad events `A : ι → Set Ω` and a finite index set `S`, `bset A S` is the
event that none of the bad events indexed by `S` occurs:
`bset A S = ⋂ j ∈ S, (A j)ᶜ` (with the convention `bset A ∅ = Set.univ`). -/
def bset (A : ι → Set Ω) (S : Finset ι) : Set Ω := ⋂ j ∈ S, (A j)ᶜ

/-- `IsDependencyGraph G A` is the avoidance-event formulation of the dependency-graph hypothesis
of the Lovász local lemma:
for every index `i` and every finite set `S` of non-neighbors of `i` with `i ∉ S`, the bad event
`A i` is independent of the event `bset A S` that none of the bad events indexed by `S` occurs. -/
def IsDependencyGraph (G : SimpleGraph ι) (A : ι → Set Ω) : Prop :=
  ∀ i (S : Finset ι), i ∉ S → (∀ j ∈ S, ¬ G.Adj i j) → IndepSet (A i) (bset A S) μ

omit [MeasurableSpace Ω] [Fintype ι] [DecidableEq ι] in
/-- The bad-event set of the empty index set is the whole space. -/
lemma bset_empty (A : ι → Set Ω) : bset A ∅ = Set.univ := by
  simp [bset]

attribute [simp] bset_empty

omit [MeasurableSpace Ω] [Fintype ι] in
/-- Inserting an index prepends the complement of its bad event: the event that none of the bad
events indexed by `insert r S` occurs is the intersection of `(A r)ᶜ` with `bset A S`. -/
lemma bset_insert (A : ι → Set Ω) (r : ι) (S : Finset ι) :
    bset A (insert r S) = (A r)ᶜ ∩ bset A S := by
  simp [bset]

attribute [simp] bset_insert

omit [MeasurableSpace Ω] [Fintype ι] [DecidableEq ι] in
/-- `bset` is antitone in the index set: enlarging the index set shrinks the event that none of
the bad events indexed by `S` occurs. -/
lemma bset_subset_bset_of_subset (A : ι → Set Ω) {S T : Finset ι} (h : S ⊆ T) :
    bset A T ⊆ bset A S := by
  intro ω hω
  simp only [bset, Set.mem_iInter] at hω ⊢
  intro j hj
  exact hω j (h hj)

omit [MeasurableSpace Ω] [Fintype ι] in
/-- Avoiding all bad events indexed by a union is the same as avoiding those indexed by each
part: `bset A (S ∪ T) = bset A S ∩ bset A T`. -/
lemma bset_union (A : ι → Set Ω) {S T : Finset ι} :
    bset A (S ∪ T) = bset A S ∩ bset A T := by
  ext ω
  simp only [bset, Set.mem_iInter, Set.mem_inter_iff]
  constructor <;> intro hω
  · constructor <;> intro j hj
    · exact hω j (Finset.mem_union.mpr (Or.inl hj))
    · exact hω j (Finset.mem_union.mpr (Or.inr hj))
  · intro j hj
    rcases Finset.mem_union.mp hj with hjS | hjT
    · exact hω.1 j hjS
    · exact hω.2 j hjT

attribute [simp] bset_union

omit [MeasurableSpace Ω] [DecidableEq ι] in
/-- the bridge between the Finset-indexed and unbounded forms — `bset` over all
indices is the intersection of all complements. -/
lemma bset_univ_eq_iInter (A : ι → Set Ω) : bset A Finset.univ = ⋂ i, (A i)ᶜ := by
  ext ω
  simp [bset]

attribute [simp] bset_univ_eq_iInter

omit [Fintype ι] [DecidableEq ι] in
/-- If every bad event is measurable, so is every `bset`. -/
lemma measurableSet_bset (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i)) (S : Finset ι) :
    MeasurableSet (bset A S) := by
  simp only [bset]
  exact Finset.measurableSet_biInter S (fun i _ => (hA i).compl)

attribute [measurability] measurableSet_bset

/-- The ENNReal glue: `ofReal (1 - x) = 1 - ofReal x` for `0 ≤ x`. -/
lemma ofReal_one_sub {x : ℝ} (hx : 0 ≤ x) :
    ENNReal.ofReal (1 - x) = 1 - ENNReal.ofReal x := by
  simpa using (ENNReal.ofReal_sub 1 hx)

omit [Fintype ι] in
/-- Peeling identity: inserting an index into the index set peels off its bad event — the measure
of the event that none of the bad events indexed by `insert r S` occurs equals the measure of
`bset A S` minus the "bad part" `A r ∩ bset A S` (a disjoint splitting, valid since `μ` is a
probability measure). -/
lemma measure_bset_insert (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {S : Finset ι} {r : ι} :
    μ (bset A (insert r S)) = μ (bset A S) - μ (A r ∩ bset A S) := by
  rw [bset_insert]
  rw [ENNReal.sub_eq_of_eq_add (measure_ne_top μ (A r ∩ bset A S))]
  rw [← measure_inter_add_sdiff (bset A S) (hA r)]
  rw [Set.inter_comm, Set.sdiff_eq, Set.inter_comm]
  ac_rfl

omit [Fintype ι] in
/-- One-step peeling bound: if the "bad part" of the peel is controlled at `(r, S)` via `hP2`,
the measure of `bset A (insert r S)` is at least `ofReal (1 - x r) * μ (bset A S)`. -/
lemma measure_bset_insert_le (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) {S : Finset ι} {r : ι}
    (hP2 : μ (A r ∩ bset A S) ≤ ENNReal.ofReal (x r) * μ (bset A S)) :
    ENNReal.ofReal (1 - x r) * μ (bset A S) ≤ μ (bset A (insert r S)) := by
  rw [ofReal_one_sub (hx₀ r)]
  rw [ENNReal.sub_mul (fun _ _ => measure_ne_top μ (bset A S))]
  rw [one_mul, measure_bset_insert A hA]
  exact tsub_le_tsub_left hP2 (μ (bset A S))

omit [Fintype ι] in
/-- Product-chain bound — the order-free replacement for the classical chain rule: for disjoint
`N, M`, the product bound at `M` lifts to `N ∪ M`. `hP2` is the P2-invariant at every subset
`U ⊆ M ∪ N` (the shape the strong-induction IH of item 60.1 provides). -/
lemma prob_bset_inter_prod (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    {N M : Finset ι} (hNM : Disjoint N M)
    (hP2 : ∀ (U : Finset ι), U ⊆ M ∪ N → ∀ i, i ∈ N → i ∉ U →
      μ (A i ∩ bset A U) ≤ ENNReal.ofReal (x i) * μ (bset A U)) :
    ENNReal.ofReal (∏ j ∈ N, (1 - x j)) * μ (bset A M) ≤ μ (bset A (N ∪ M)) := by
  induction N using Finset.induction with
  | empty =>
      simp
  | insert r N' hr ih =>
      have hpeel : ENNReal.ofReal (1 - x r) * μ (bset A (N' ∪ M)) ≤
          μ (bset A (insert r (N' ∪ M))) := by
        refine measure_bset_insert_le A hA hx₀ ?_
        have hUsub : N' ∪ M ⊆ M ∪ insert r N' := by
          rw [Finset.union_comm]
          exact Finset.union_subset_union_right (Finset.subset_insert r N')
        have hrM : r ∉ M := (Finset.disjoint_left.mp hNM) (Finset.mem_insert_self r N')
        have hrU : r ∉ N' ∪ M := by
          simp [hr, hrM]
        exact hP2 (N' ∪ M) hUsub r (Finset.mem_insert_self r N') hrU
      have hih : ENNReal.ofReal (∏ j ∈ N', (1 - x j)) * μ (bset A M) ≤ μ (bset A (N' ∪ M)) := by
        refine ih (Disjoint.mono_left (Finset.subset_insert r N') hNM) ?_
        intro U hU i hi hiu
        exact hP2 U (hU.trans (Finset.union_subset_union_right (Finset.subset_insert r N'))) i
          (Finset.mem_insert.mpr (Or.inr hi)) hiu
      calc
        ENNReal.ofReal (∏ j ∈ insert r N', (1 - x j)) * μ (bset A M)
            = ENNReal.ofReal ((1 - x r) * ∏ j ∈ N', (1 - x j)) * μ (bset A M) := by
                rw [Finset.prod_insert hr]
        _ = (ENNReal.ofReal (1 - x r) * ENNReal.ofReal (∏ j ∈ N', (1 - x j))) * μ (bset A M) := by
                rw [ENNReal.ofReal_mul (sub_nonneg.mpr (le_of_lt (hx₁ r)))]
        _ = ENNReal.ofReal (1 - x r) * (ENNReal.ofReal (∏ j ∈ N', (1 - x j)) * μ (bset A M)) := by
                rw [mul_assoc]
        _ ≤ ENNReal.ofReal (1 - x r) * μ (bset A (N' ∪ M)) := by
                exact mul_le_mul_right hih (ENNReal.ofReal (1 - x r))
        _ ≤ μ (bset A (insert r (N' ∪ M))) := hpeel
        _ = μ (bset A (insert r N' ∪ M)) := by
                rw [← Finset.insert_union]

omit [DecidableEq ι] in
/-- The (P1)+(P2) strong induction — the heart of the Lovász local lemma proof: under the full
LLL hypotheses, for every finite `S : Finset ι`, simultaneously (P1)
`ENNReal.ofReal (∏ j ∈ S, (1 - x j)) ≤ μ (bset A S)` and (P2)
`i ∉ S → μ (A i ∩ bset A S) ≤ ENNReal.ofReal (x i) * μ (bset A S)`. -/
theorem lll_prob_bset (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)))
    (S : Finset ι) :
    ENNReal.ofReal (∏ j ∈ S, (1 - x j)) ≤ μ (bset A S) ∧
    ∀ i, i ∉ S → μ (A i ∩ bset A S) ≤ ENNReal.ofReal (x i) * μ (bset A S) := by
  classical
  refine Finset.strongInductionOn S ?_
  intro S ih
  have hμi (i : ι) : μ (A i) ≤ ENNReal.ofReal (x i) := by
    calc
      μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)) := hLLL i
      _ = ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) := by
          rw [ENNReal.ofReal_mul (hx₀ i)]
      _ ≤ ENNReal.ofReal (x i) := by
          have hprod : ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) ≤ 1 := by
            rw [ENNReal.ofReal_prod_of_nonneg (fun j _ => sub_nonneg.mpr (le_of_lt (hx₁ j)))]
            refine Finset.prod_le_one' ?_
            intro j hj
            simpa using (ENNReal.ofReal_le_ofReal (by linarith [hx₀ j] : 1 - x j ≤ 1))
          simpa using mul_le_mul_right hprod (ENNReal.ofReal (x i))
  by_cases hS : S = ∅
  · subst S
    constructor
    · simp
    · intro i hi
      simp
      exact hμi i
  · constructor
    · have hSne : S.Nonempty := Finset.nonempty_iff_ne_empty.mpr hS
      obtain ⟨r, hr⟩ := hSne
      have hT : S.erase r ⊂ S := Finset.erase_ssubset hr
      have ihP1 : ENNReal.ofReal (∏ j ∈ S.erase r, (1 - x j)) ≤ μ (bset A (S.erase r)) :=
        (ih (S.erase r) hT).1
      have ihP2r : μ (A r ∩ bset A (S.erase r)) ≤
          ENNReal.ofReal (x r) * μ (bset A (S.erase r)) := by
        exact (ih (S.erase r) hT).2 r (Finset.notMem_erase r S)
      calc
        ENNReal.ofReal (∏ j ∈ S, (1 - x j))
            = ENNReal.ofReal ((1 - x r) * ∏ j ∈ S.erase r, (1 - x j)) := by
                rw [← Finset.mul_prod_erase S (fun j => 1 - x j) hr]
        _ = ENNReal.ofReal (1 - x r) * ENNReal.ofReal (∏ j ∈ S.erase r, (1 - x j)) := by
                rw [ENNReal.ofReal_mul (sub_nonneg.mpr (le_of_lt (hx₁ r)))]
        _ ≤ ENNReal.ofReal (1 - x r) * μ (bset A (S.erase r)) := by
                exact mul_le_mul_right ihP1 (ENNReal.ofReal (1 - x r))
        _ ≤ μ (bset A (insert r (S.erase r))) := by
                exact measure_bset_insert_le A hA hx₀ ihP2r
        _ = μ (bset A S) := by
                rw [Finset.insert_erase hr]
    · intro i hiS
      let N := S.filter (fun j => G.Adj i j)
      let M := S.filter (fun j => ¬ G.Adj i j)
      by_cases hN : N = ∅
      · have hnonadjS : ∀ j ∈ S, ¬ G.Adj i j := by
          intro j hjS hAdj
          have hjN : j ∈ N := Finset.mem_filter.mpr ⟨hjS, hAdj⟩
          rw [hN] at hjN
          exact Finset.notMem_empty j hjN
        have hind : μ (A i ∩ bset A S) = μ (A i) * μ (bset A S) := by
          exact (indepSet_iff_measure_inter_eq_mul (μ := μ) (hA i) (measurableSet_bset A hA S)).mp
            (hdg i S hiS hnonadjS)
        calc
          μ (A i ∩ bset A S) = μ (A i) * μ (bset A S) := hind
          _ ≤ ENNReal.ofReal (x i) * μ (bset A S) := mul_le_mul_left (hμi i) (μ (bset A S))
      · have hNM : Disjoint N M := by
          rw [Finset.disjoint_left]
          intro j hjN hjM
          exact (Finset.mem_filter.mp hjM).2 (Finset.mem_filter.mp hjN).2
        have hSMN : N ∪ M = S := Finset.filter_union_filter_not_eq (fun j => G.Adj i j) S
        have hP2' : ∀ (U : Finset ι), U ⊆ M ∪ N → ∀ k, k ∈ N → k ∉ U →
            μ (A k ∩ bset A U) ≤ ENNReal.ofReal (x k) * μ (bset A U) := by
          intro U hU k hkN hkU
          have hkS : k ∈ S := (Finset.mem_filter.mp hkN).1
          have hUS : U ⊆ S := by
            rw [← hSMN]
            simpa [Finset.union_comm] using hU
          have hUne : U ≠ S := by
            intro h
            exact hkU (by simpa [h] using hkS)
          have hUss : U ⊂ S := Finset.ssubset_iff_subset_ne.mpr ⟨hUS, hUne⟩
          exact (ih U hUss).2 k hkU
        have hMS : M ⊆ S := Finset.filter_subset (fun j => ¬ G.Adj i j) S
        have hiM : i ∉ M := fun h => hiS (Finset.filter_subset (fun j => ¬ G.Adj i j) S h)
        have hnonadjM : ∀ j ∈ M, ¬ G.Adj i j := by
          intro j hjM
          exact (Finset.mem_filter.mp hjM).2
        have hindM : μ (A i ∩ bset A M) = μ (A i) * μ (bset A M) := by
          exact (indepSet_iff_measure_inter_eq_mul (μ := μ) (hA i) (measurableSet_bset A hA M)).mp
            (hdg i M hiM hnonadjM)
        have hNΓ : N ⊆ G.neighborFinset i := by
          intro j hjN
          simpa using (Finset.mem_filter.mp hjN).2
        have hLLLi : μ (A i) ≤
            ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) := by
          calc
            μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)) := hLLL i
            _ = ENNReal.ofReal (x i) *
                ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) := by
                rw [ENNReal.ofReal_mul (hx₀ i)]
        have hLLL' : μ (A i) * μ (bset A M) ≤
            ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) *
              μ (bset A M) := by
          exact mul_le_mul_left hLLLi (μ (bset A M))
        have hofN : ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) ≤
            ENNReal.ofReal (∏ j ∈ N, (1 - x j)) := by
          rw [ENNReal.ofReal_prod_of_nonneg (fun j _ => sub_nonneg.mpr (le_of_lt (hx₁ j)))]
          rw [ENNReal.ofReal_prod_of_nonneg (fun j _ => sub_nonneg.mpr (le_of_lt (hx₁ j)))]
          refine Finset.prod_le_prod_of_subset_of_le_one' hNΓ ?_
          intro j hj hjn
          simpa using (ENNReal.ofReal_le_ofReal (by linarith [hx₀ j] : 1 - x j ≤ 1))
        have h4 : ENNReal.ofReal (x i) *
            ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) * μ (bset A M) ≤
            ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ N, (1 - x j)) * μ (bset A M) := by
          exact mul_le_mul_left (mul_le_mul_right hofN (ENNReal.ofReal (x i))) (μ (bset A M))
        have h5 : ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ N, (1 - x j)) * μ (bset A M) ≤
            ENNReal.ofReal (x i) * μ (bset A (N ∪ M)) := by
          rw [mul_assoc]
          exact mul_le_mul_right (prob_bset_inter_prod A hA hx₀ hx₁ hNM hP2')
            (ENNReal.ofReal (x i))
        calc
          μ (A i ∩ bset A S) ≤ μ (A i ∩ bset A M) := by
            exact measure_mono (by simpa [Set.inter_comm] using
              (Set.inter_subset_inter_left (A i) (bset_subset_bset_of_subset A hMS)))
          _ = μ (A i) * μ (bset A M) := hindM
          _ ≤ ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ G.neighborFinset i, (1 - x j)) *
              μ (bset A M) := hLLL'
          _ ≤ ENNReal.ofReal (x i) * ENNReal.ofReal (∏ j ∈ N, (1 - x j)) * μ (bset A M) := h4
          _ ≤ ENNReal.ofReal (x i) * μ (bset A (N ∪ M)) := h5
          _ = ENNReal.ofReal (x i) * μ (bset A S) := by rw [hSMN]

omit [DecidableEq ι] in
/-- The asymmetric Lovász Local Lemma: if each bad event `A i` has probability at most
`x i * ∏ j ∈ G.neighborFinset i, (1 - x j)` for weights `x i ∈ [0, 1)`, then the probability
that none occurs is at least `∏ i, (1 - x i)`. -/
theorem lovaszLocalLemma (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j))) :
    ENNReal.ofReal (∏ i, (1 - x i)) ≤ μ (⋂ i, (A i)ᶜ) := by
  simpa using (lll_prob_bset A hA hdg hx₀ hx₁ hLLL Finset.univ).1

omit [DecidableEq ι] in
/-- Existence form of the asymmetric LLL: with positive probability, none of the bad events
occurs. -/
theorem lovaszLocalLemma_pos (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j))) :
    0 < μ (⋂ i, (A i)ᶜ) := by
  have hprod : 0 < ∏ i, (1 - x i) := Finset.prod_pos (fun i hi => sub_pos.mpr (hx₁ i))
  have hofReal : 0 < ENNReal.ofReal (∏ i, (1 - x i)) := ENNReal.ofReal_pos.mpr hprod
  exact lt_of_lt_of_le hofReal (lovaszLocalLemma A hA hdg hx₀ hx₁ hLLL)

omit [DecidableEq ι] in
/-- ℝ-valued corollary of the asymmetric LLL via `μ.real`: the product bound holds for the
real-valued probability of avoiding all bad events. -/
theorem lovaszLocalLemma_probReal (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j))) :
    ∏ i, (1 - x i) ≤ μ.real (⋂ i, (A i)ᶜ) := by
  exact (ENNReal.ofReal_le_iff_le_toReal (measure_ne_top μ (⋂ i, (A i)ᶜ))).mp
    (lovaszLocalLemma A hA hdg hx₀ hx₁ hLLL)

omit [IsProbabilityMeasure μ] [Fintype ι] [DecidableEq ι] in
/-- `IsDependencyGraphStrong G A` is the generated-σ-algebra formulation of the dependency-graph
hypothesis of the Lovász local lemma ([alonSpencer2016]): for every index `i`, the bad event
`A i` is independent of the σ-algebra generated by all non-neighbor bad events `A j`
(`j ≠ i`, `¬ G.Adj i j`) — equivalently, `A i` is independent of every Boolean combination of
the non-neighbor events. -/
def IsDependencyGraphStrong (G : SimpleGraph ι) (A : ι → Set Ω) : Prop :=
  ∀ i, Indep (MeasurableSpace.generateFrom {A i})
    (MeasurableSpace.generateFrom {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = A j}) μ

omit [IsProbabilityMeasure μ] [Fintype ι] [DecidableEq ι] in
/-- The generated-σ-algebra formulation of the dependency-graph hypothesis implies the
avoidance-event one (`IsDependencyGraph`): independence from the σ-algebra generated by all
non-neighbor events implies independence from the finite intersection `bset A S` of their
complements. -/
theorem IsDependencyGraph.of_strong {G : SimpleGraph ι} {A : ι → Set Ω}
    (h : IsDependencyGraphStrong (μ := μ) G A) : IsDependencyGraph (μ := μ) G A := by
  intro i S hiS hnonadj
  have hAi : MeasurableSet[MeasurableSpace.generateFrom {A i}] (A i) :=
    MeasurableSpace.measurableSet_generateFrom rfl
  have hB : MeasurableSet[MeasurableSpace.generateFrom
      {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = A j}] (bset A S) := by
    have hle : MeasurableSpace.generateFrom {A j | j ∈ S} ≤
        MeasurableSpace.generateFrom {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = A j} :=
      MeasurableSpace.generateFrom_mono (by
        rintro t ⟨j, hjS, rfl⟩
        exact ⟨j, fun hij => hiS (hij ▸ hjS), hnonadj j hjS, rfl⟩)
    have hB' : MeasurableSet[MeasurableSpace.generateFrom {A j | j ∈ S}] (bset A S) := by
      letI : MeasurableSpace Ω := MeasurableSpace.generateFrom {A j | j ∈ S}
      simp only [bset]
      exact Finset.measurableSet_biInter S (fun j hj =>
        (MeasurableSpace.measurableSet_generateFrom
          (show A j ∈ {A k | k ∈ S} from ⟨j, hj, rfl⟩)).compl)
    exact hle _ hB'
  exact Indep.indepSet_of_measurableSet (μ := μ) (h i) hAi hB

omit [Fintype ι] in
/-- The avoidance-event formulation of the dependency-graph hypothesis implies the
generated-σ-algebra one when every bad event is measurable: independence from every finite
intersection `bset A U` of non-neighbor complements lifts through the π-system of such
intersections (`IndepSets.indep'`) to independence of the generated σ-algebras. -/
theorem IsDependencyGraph.strong {G : SimpleGraph ι} {A : ι → Set Ω}
    (hA : ∀ i, MeasurableSet (A i)) (h : IsDependencyGraph (μ := μ) G A) :
    IsDependencyGraphStrong (μ := μ) G A := by
  intro i
  let p2 : Set (Set Ω) :=
    {u | ∃ U : Finset ι, i ∉ U ∧ (∀ j ∈ U, ¬ G.Adj i j) ∧ u = bset A U}
  have hp1m : ∀ s ∈ ({A i} : Set (Set Ω)), MeasurableSet s := by
    rintro s rfl
    exact hA i
  have hp2m : ∀ s ∈ p2, MeasurableSet s := by
    rintro s ⟨U, hiU, hnU, rfl⟩
    exact measurableSet_bset A hA U
  have hpi1 : IsPiSystem ({A i} : Set (Set Ω)) := by
    rintro s rfl t rfl _
    exact Set.inter_self (A i)
  have hpi2 : IsPiSystem p2 := by
    rintro u ⟨U, hiU, hnU, rfl⟩ v ⟨V, hiV, hnV, rfl⟩ _
    refine ⟨U ∪ V, ?_, ?_, ?_⟩
    · intro hi
      rw [Finset.mem_union] at hi
      exact hi.elim hiU hiV
    · intro j hj
      rw [Finset.mem_union] at hj
      exact hj.elim (hnU j) (hnV j)
    · simp
  have hIndepSets : IndepSets ({A i} : Set (Set Ω)) p2 μ := by
    rw [IndepSets_iff]
    intro s t hs ht
    rw [Set.mem_singleton_iff] at hs
    subst s
    obtain ⟨U, hiU, hnU, rfl⟩ := ht
    exact (indepSet_iff_measure_inter_eq_mul (μ := μ) (hA i) (measurableSet_bset A hA U)).mp
      (h i U hiU hnU)
  have hind : Indep (MeasurableSpace.generateFrom ({A i} : Set (Set Ω)))
      (MeasurableSpace.generateFrom p2) μ :=
    IndepSets.indep' (μ := μ) hp1m hp2m hpi1 hpi2 hIndepSets
  have hgen1 : MeasurableSpace.generateFrom p2 = MeasurableSpace.generateFrom
      {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = (A j)ᶜ} := by
    refine le_antisymm (MeasurableSpace.generateFrom_le ?_)
      (MeasurableSpace.generateFrom_mono ?_)
    · rintro u ⟨U, hiU, hnU, rfl⟩
      letI : MeasurableSpace Ω :=
        MeasurableSpace.generateFrom {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = (A j)ᶜ}
      simp only [bset]
      exact Finset.measurableSet_biInter U (fun k hk =>
        MeasurableSpace.measurableSet_generateFrom
          ⟨k, fun hki => hiU (hki ▸ hk), hnU k hk, rfl⟩)
    · rintro t ⟨j, hji, hnj, rfl⟩
      refine ⟨{j}, ?_, ?_, ?_⟩
      · intro hx
        exact hji (Finset.mem_singleton.mp hx).symm
      · intro k hk
        rw [Finset.mem_singleton.mp hk]
        exact hnj
      · simp [bset]
  have hgen2 : MeasurableSpace.generateFrom
      {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = (A j)ᶜ} =
      MeasurableSpace.generateFrom {t : Set Ω | ∃ j, j ≠ i ∧ ¬ G.Adj i j ∧ t = A j} := by
    refine le_antisymm (MeasurableSpace.generateFrom_le ?_)
      (MeasurableSpace.generateFrom_le ?_)
    · rintro t ⟨j, hji, hnj, rfl⟩
      exact (MeasurableSpace.measurableSet_generateFrom
        (show A j ∈ ({t : Set Ω | ∃ k, k ≠ i ∧ ¬ G.Adj i k ∧ t = A k}) from
          ⟨j, hji, hnj, rfl⟩)).compl
    · rintro t ⟨j, hji, hnj, rfl⟩
      simpa using (MeasurableSpace.measurableSet_generateFrom
        (show (A j)ᶜ ∈ ({t : Set Ω | ∃ k, k ≠ i ∧ ¬ G.Adj i k ∧ t = (A k)ᶜ}) from
          ⟨j, hji, hnj, rfl⟩)).compl
  rw [hgen1, hgen2] at hind
  exact hind

omit [Fintype ι] in
/-- The two formulations of the dependency-graph hypothesis are equivalent (when every bad event
is measurable): the avoidance-event formulation and the generated-σ-algebra formulation. -/
theorem isDependencyGraph_iff_strong {G : SimpleGraph ι} {A : ι → Set Ω}
    (hA : ∀ i, MeasurableSet (A i)) :
    IsDependencyGraph (μ := μ) G A ↔ IsDependencyGraphStrong (μ := μ) G A :=
  ⟨IsDependencyGraph.strong hA, IsDependencyGraph.of_strong⟩

omit [DecidableEq ι] in
/-- Existence-witness form of the asymmetric LLL: some outcome avoids every bad event. -/
theorem lovaszLocalLemma_exists (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j))) :
    ∃ ω, ∀ i, ω ∉ A i := by
  obtain ⟨ω, hω⟩ := nonempty_of_measure_ne_zero
    (ne_of_gt (lovaszLocalLemma_pos A hA hdg hx₀ hx₁ hLLL))
  refine ⟨ω, ?_⟩
  simpa using hω

omit [DecidableEq ι] in
/-- The symmetric Lovász local lemma with the optimal uniform weight (cf. [alonSpencer2016]): if
every bad event has probability at most `p`, every vertex of the dependency graph has degree at
most `d ≥ 1`, and `p` satisfies the smallness condition `(d+1)^(d+1) · p ≤ d^d` (the optimal
constant for the uniform weight `1/(d+1)`, the maximizer of `x(1-x)^d`), then some outcome avoids
all bad events: `0 < μ (⋂ i, (A i)ᶜ)`. -/
theorem lovaszLocalLemma_symmetric_optimalWeight (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {p : ℝ} (hp : ∀ i, μ (A i) ≤ ENNReal.ofReal p) {d : ℕ}
    (hd : ∀ i, G.degree i ≤ d) (hd₁ : 1 ≤ d)
    (hcond : ((d : ℝ) + 1) ^ (d + 1) * p ≤ (d : ℝ) ^ d) :
    0 < μ (⋂ i, (A i)ᶜ) := by
  let x : ι → ℝ := fun _ => 1 / ((d : ℝ) + 1)
  have hdpos : 0 < (d : ℝ) + 1 := by exact_mod_cast Nat.succ_pos d
  have hdnz : ((d : ℝ) + 1) ≠ 0 := ne_of_gt hdpos
  have hx₀ : ∀ i, 0 ≤ x i := by
    intro i
    change 0 ≤ 1 / ((d : ℝ) + 1)
    exact div_nonneg zero_le_one (le_of_lt hdpos)
  have hx₁ : ∀ i, x i < 1 := by
    intro i
    have hd₁ℝ : (1 : ℝ) ≤ (d : ℝ) := by exact_mod_cast hd₁
    change 1 / ((d : ℝ) + 1) < 1
    exact (div_lt_one hdpos).2 (by linarith)
  have hLLL : ∀ i,
      μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)) := by
    intro i
    have hstep1 : p ≤ (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) :=
      (le_div_iff₀ (pow_pos hdpos (d + 1))).mpr (by simpa [mul_comm] using hcond)
    have hstep2 : (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) =
        (1 / ((d : ℝ) + 1)) * ((d : ℝ) / ((d : ℝ) + 1)) ^ d := by
      rw [div_pow]
      field_simp [hdnz, pow_ne_zero d hdnz, pow_ne_zero (d + 1) hdnz]
      ring
    have hpow : ((d : ℝ) / ((d : ℝ) + 1)) ^ d ≤
        ((d : ℝ) / ((d : ℝ) + 1)) ^ G.degree i := by
      refine pow_le_pow_of_le_one ?_ ?_ (hd i)
      · exact div_nonneg (Nat.cast_nonneg d) (le_of_lt hdpos)
      · exact (div_le_one hdpos).2 (by linarith)
    have hchain : p ≤ x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
      calc
        p ≤ (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) := hstep1
        _ = (1 / ((d : ℝ) + 1)) * ((d : ℝ) / ((d : ℝ) + 1)) ^ d := hstep2
        _ ≤ (1 / ((d : ℝ) + 1)) * ((d : ℝ) / ((d : ℝ) + 1)) ^ G.degree i :=
            mul_le_mul_of_nonneg_left hpow (hx₀ i)
        _ = x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
            change (1 / ((d : ℝ) + 1)) * ((d : ℝ) / ((d : ℝ) + 1)) ^ G.degree i =
              (1 / ((d : ℝ) + 1)) * ∏ j ∈ G.neighborFinset i, (1 - 1 / ((d : ℝ) + 1))
            have hfactor : 1 - 1 / ((d : ℝ) + 1) = (d : ℝ) / ((d : ℝ) + 1) := by
              field_simp [hdnz]
              ring
            simp_rw [hfactor]
            rw [Finset.prod_const]
            rfl
    exact le_trans (hp i) (ENNReal.ofReal_le_ofReal hchain)
  exact lovaszLocalLemma_pos A hA hdg hx₀ hx₁ hLLL

omit [DecidableEq ι] in
/-- The classical symmetric Lovász local lemma: with `e·p·(d+1) ≤ 1`, some outcome
avoids all bad events. -/
theorem lovaszLocalLemma_symmetric (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {p : ℝ} (hp : ∀ i, μ (A i) ≤ ENNReal.ofReal p) {d : ℕ}
    (hd : ∀ i, G.degree i ≤ d) (hcond : Real.exp 1 * p * ((d : ℝ) + 1) ≤ 1) :
    0 < μ (⋂ i, (A i)ᶜ) := by
  by_cases hd1 : 1 ≤ d
  · have hdposℝ : 0 < (d : ℝ) := Nat.cast_pos.mpr (Nat.succ_le_iff.mp hd1)
    have hdnz : (d : ℝ) ≠ 0 := ne_of_gt hdposℝ
    have hdpos1 : 0 < (d : ℝ) + 1 := by exact_mod_cast Nat.succ_pos d
    have hdnz1 : ((d : ℝ) + 1) ≠ 0 := ne_of_gt hdpos1
    have hp1 : p ≤ 1 / (Real.exp 1 * ((d : ℝ) + 1)) :=
      (le_div_iff₀ (mul_pos (Real.exp_pos 1) hdpos1)).mpr
        (by simpa [mul_assoc, mul_comm, mul_left_comm] using hcond)
    have hfrac : (d : ℝ) / ((d : ℝ) + 1) = (1 + (d : ℝ)⁻¹)⁻¹ := by
      field_simp [hdnz]
    have hpos1 : 0 < 1 + (d : ℝ)⁻¹ := by positivity
    have hpow : (1 + (d : ℝ)⁻¹) ^ d ≤ Real.exp 1 :=
      Real.one_add_inv_pow_le_exp (n := d)
    have h2b : 1 / Real.exp 1 ≤ ((d : ℝ) / ((d : ℝ) + 1)) ^ d := by
      calc
        1 / Real.exp 1 ≤ 1 / (1 + (d : ℝ)⁻¹) ^ d :=
          one_div_le_one_div_of_le (pow_pos hpos1 d) hpow
        _ = ((1 + (d : ℝ)⁻¹)⁻¹) ^ d := by
          rw [inv_pow]
          simp
        _ = ((d : ℝ) / ((d : ℝ) + 1)) ^ d := by
          rw [← hfrac]
    have h2 : 1 / (Real.exp 1 * ((d : ℝ) + 1)) ≤
        (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) := by
      calc
        1 / (Real.exp 1 * ((d : ℝ) + 1)) = (1 / ((d : ℝ) + 1)) * (1 / Real.exp 1) := by
          rw [one_div_mul_one_div]
          ring
        _ ≤ (1 / ((d : ℝ) + 1)) * ((d : ℝ) / ((d : ℝ) + 1)) ^ d :=
          mul_le_mul_of_nonneg_left h2b (div_nonneg zero_le_one (le_of_lt hdpos1))
        _ = (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) := by
          rw [div_pow]
          field_simp [hdnz1, pow_ne_zero d hdnz1, pow_ne_zero (d + 1) hdnz1]
          ring
    have hp_frac : p ≤ (d : ℝ) ^ d / ((d : ℝ) + 1) ^ (d + 1) := le_trans hp1 h2
    have hcond' : ((d : ℝ) + 1) ^ (d + 1) * p ≤ (d : ℝ) ^ d := by
      simpa [mul_comm] using (le_div_iff₀ (pow_pos hdpos1 (d + 1))).mp hp_frac
    exact lovaszLocalLemma_symmetric_optimalWeight A hA hdg hp hd hd1 hcond'
  · have hd0 : d = 0 := by omega
    subst d
    have hp1 : p ≤ 1 / Real.exp 1 :=
      (le_div_iff₀ (Real.exp_pos 1)).mpr
        (by simpa [mul_assoc, mul_comm, mul_left_comm] using hcond)
    have h12 : 1 / Real.exp 1 ≤ (1 : ℝ) / 2 := by
      refine one_div_le_one_div_of_le (by norm_num) ?_
      linarith [Real.add_one_le_exp (1 : ℝ)]
    have hp12 : p ≤ (1 : ℝ) / 2 := le_trans hp1 h12
    let x : ι → ℝ := fun _ => (1 : ℝ) / 2
    have hx₀ : ∀ i, 0 ≤ x i := by
      intro i
      dsimp [x]
      norm_num
    have hx₁ : ∀ i, x i < 1 := by
      intro i
      dsimp [x]
      norm_num
    have hLLL : ∀ i,
        μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)) := by
      intro i
      have hdeg0 : G.degree i = 0 := Nat.eq_zero_of_le_zero (hd i)
      have hiso : G.IsIsolated i := (SimpleGraph.degree_eq_zero G i).mp hdeg0
      have hchain : p ≤ x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
        calc
          p ≤ (1 : ℝ) / 2 := hp12
          _ = x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
            dsimp [x]
            simp [hiso.neighborFinset_eq_empty]
      exact le_trans (hp i) (ENNReal.ofReal_le_ofReal hchain)
    exact lovaszLocalLemma_pos A hA hdg hx₀ hx₁ hLLL

omit [DecidableEq ι] in
/-- The `4pd` criterion for the symmetric Lovász local lemma: if every bad event has
probability at most `p` and every vertex of the dependency graph has degree at most
`d ≥ 1`, with `4·p·d ≤ 1`, then some outcome avoids all bad events:
`0 < μ (⋂ i, (A i)ᶜ)`. -/
theorem lovaszLocalLemma_4pd (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {p : ℝ} (hp : ∀ i, μ (A i) ≤ ENNReal.ofReal p) {d : ℕ}
    (hd : ∀ i, G.degree i ≤ d) (hd₀ : 1 ≤ d) (hcond : 4 * p * (d : ℝ) ≤ 1) :
    0 < μ (⋂ i, (A i)ᶜ) := by
  let x : ι → ℝ := fun _ => 1 / (2 * (d : ℝ))
  have hdℝ : (1 : ℝ) ≤ (d : ℝ) := by exact_mod_cast hd₀
  have hdpos : 0 < (d : ℝ) := Nat.cast_pos.mpr (Nat.succ_le_iff.mp hd₀)
  have hdnz : (d : ℝ) ≠ 0 := ne_of_gt hdpos
  have h2dpos : 0 < 2 * (d : ℝ) := by positivity
  have h4dpos : 0 < 4 * (d : ℝ) := by positivity
  have hx₀ : ∀ i, 0 ≤ x i := by
    intro i
    change 0 ≤ 1 / (2 * (d : ℝ))
    exact div_nonneg zero_le_one (le_of_lt h2dpos)
  have hx₁ : ∀ i, x i < 1 := by
    intro i
    change 1 / (2 * (d : ℝ)) < 1
    exact (div_lt_one h2dpos).2 (by linarith)
  have hLLL : ∀ i,
      μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)) := by
    intro i
    -- Bernoulli: `1/2 ≤ (1 - 1/(2d))^d` via `one_add_mul_le_pow` at `a = -1/(2d)`.
    have h12d : 1 / (2 * (d : ℝ)) ≤ (2 : ℝ) :=
      (div_le_iff₀ h2dpos).mpr (by linarith)
    have hbernoulli : 1 + (d : ℝ) * (-(1 / (2 * (d : ℝ)))) ≤
        (1 + (-(1 / (2 * (d : ℝ))))) ^ d := one_add_mul_le_pow (by linarith) d
    have hb : (1 : ℝ) / 2 ≤ (1 - 1 / (2 * (d : ℝ))) ^ d := by
      have hb' : 1 + (d : ℝ) * (-(1 / (2 * (d : ℝ)))) = (1 : ℝ) / 2 := by
        field_simp [hdnz]
        ring
      have hb'' : 1 + (-(1 / (2 * (d : ℝ)))) = 1 - 1 / (2 * (d : ℝ)) := by
        ring
      rwa [hb', hb''] at hbernoulli
    -- degree monotonicity
    have hpow : (1 - 1 / (2 * (d : ℝ))) ^ d ≤
        (1 - 1 / (2 * (d : ℝ))) ^ G.degree i := by
      refine pow_le_pow_of_le_one ?_ ?_ (hd i)
      · exact sub_nonneg.mpr ((div_le_one h2dpos).2 (by linarith))
      · linarith [div_nonneg zero_le_one (le_of_lt h2dpos)]
    have hdeg : (1 : ℝ) / 2 ≤ (1 - 1 / (2 * (d : ℝ))) ^ G.degree i :=
      le_trans hb hpow
    -- `p ≤ 1/(4d)`
    have hpfrac : p ≤ 1 / (4 * (d : ℝ)) :=
      (le_div_iff₀ h4dpos).mpr (by simpa [mul_assoc, mul_comm, mul_left_comm] using hcond)
    have hfrac : 1 / (4 * (d : ℝ)) = (1 / (2 * (d : ℝ))) * ((1 : ℝ) / 2) := by
      field_simp [hdnz]
      ring
    have hchain : p ≤ x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
      calc
        p ≤ 1 / (4 * (d : ℝ)) := hpfrac
        _ = (1 / (2 * (d : ℝ))) * ((1 : ℝ) / 2) := hfrac
        _ ≤ (1 / (2 * (d : ℝ))) * (1 - 1 / (2 * (d : ℝ))) ^ G.degree i :=
            mul_le_mul_of_nonneg_left hdeg (hx₀ i)
        _ = x i * ∏ j ∈ G.neighborFinset i, (1 - x j) := by
            change (1 / (2 * (d : ℝ))) * (1 - 1 / (2 * (d : ℝ))) ^ G.degree i =
              (1 / (2 * (d : ℝ))) * ∏ j ∈ G.neighborFinset i, (1 - 1 / (2 * (d : ℝ)))
            rw [Finset.prod_const]
            rfl
    exact le_trans (hp i) (ENNReal.ofReal_le_ofReal hchain)
  exact lovaszLocalLemma_pos A hA hdg hx₀ hx₁ hLLL

omit [Fintype ι] [DecidableEq ι] in
/-- Conditioning on an independent event does nothing: if `s` and `t` are independent and `t` has
nonzero finite measure, the conditional probability `μ[s | t]` equals `μ s`. -/
lemma cond_eq_of_indepSet {s t : Set Ω} (hs : MeasurableSet s) (ht : MeasurableSet t)
    (hst : IndepSet s t μ) (hμt₀ : μ t ≠ 0) (hμt : μ t ≠ ∞) : μ[s | t] = μ s := by
  rw [cond_apply ht, Set.inter_comm, (indepSet_iff_measure_inter_eq_mul hs ht (μ := μ)).mp hst,
    mul_comm (μ s) (μ t), ← mul_assoc, ENNReal.inv_mul_cancel hμt₀ hμt, one_mul]

omit [Fintype ι] [DecidableEq ι] in
/-- Complement-of-the-event identity: `μ[tᶜ | s] = 1 - μ[t | s]` (the tsub is exact since
`μ[t | s] ≤ 1`, see `cond_le_one`). The `ht : MeasurableSet t` hypothesis is needed — the
identity is false without it. -/
lemma cond_compl_eq_one_sub {s t : Set Ω} (hms : MeasurableSet s) (ht : MeasurableSet t)
    (hμs₀ : μ s ≠ 0) : μ[tᶜ | s] = 1 - μ[t | s] := by
  have hsum : μ[tᶜ | s] + μ[t | s] = 1 := by
    rw [cond_apply hms, cond_apply hms]
    rw [← mul_add, ← Set.sdiff_eq, add_comm, measure_inter_add_sdiff s ht]
    exact ENNReal.inv_mul_cancel hμs₀ (measure_ne_top μ s)
  exact (ENNReal.sub_eq_of_eq_add' ENNReal.one_ne_top hsum.symm).symm

omit [Fintype ι] [DecidableEq ι] in
/-- Conditional probabilities of a probability measure are at most one. -/
lemma cond_le_one {s t : Set Ω} (hms : MeasurableSet s) (hμs₀ : μ s ≠ 0) :
    μ[t | s] ≤ 1 := by
  rw [cond_apply hms, ← ENNReal.inv_mul_cancel hμs₀ (measure_ne_top μ s)]
  exact (ENNReal.mul_le_mul_iff_right (ENNReal.inv_ne_zero.mpr (measure_ne_top μ s))
    (ENNReal.inv_ne_top.mpr hμs₀)).2 (measure_mono Set.inter_subset_left)

omit [DecidableEq ι] in
/-- Positivity of the bad-event set: under the LLL hypotheses, `bset A S` has positive measure
for every finite `S`. This is the well-definedness fact behind conditioning on `bset A S` (its
proof is exactly the `lovaszLocalLemma_pos` pattern, specialized from `univ` to `S`). -/
theorem lovaszLocalLemma_bset_pos (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)))
    (S : Finset ι) : 0 < μ (bset A S) := by
  have hprod : 0 < ∏ j ∈ S, (1 - x j) :=
    Finset.prod_pos (fun j _ => sub_pos.mpr (hx₁ j))
  have hofReal : 0 < ENNReal.ofReal (∏ j ∈ S, (1 - x j)) := ENNReal.ofReal_pos.mpr hprod
  exact lt_of_lt_of_le hofReal ((lll_prob_bset A hA hdg hx₀ hx₁ hLLL S).1)

omit [DecidableEq ι] in
/-- Conditional form of the key lemma: under the LLL hypotheses, for every finite `S` and every
`i ∉ S`, the conditional probability of `A i` given `bset A S` is at most `x i`. -/
theorem lovaszLocalLemma_cond (A : ι → Set Ω) (hA : ∀ i, MeasurableSet (A i))
    {G : SimpleGraph ι} [DecidableRel G.Adj] (hdg : IsDependencyGraph (μ := μ) G A)
    {x : ι → ℝ} (hx₀ : ∀ i, 0 ≤ x i) (hx₁ : ∀ i, x i < 1)
    (hLLL : ∀ i, μ (A i) ≤ ENNReal.ofReal (x i * ∏ j ∈ G.neighborFinset i, (1 - x j)))
    {S : Finset ι} {i : ι} (hi : i ∉ S) :
    μ[A i | bset A S] ≤ ENNReal.ofReal (x i) := by
  have hμS₀ : 0 < μ (bset A S) := lovaszLocalLemma_bset_pos A hA hdg hx₀ hx₁ hLLL S
  have hP2 : μ (A i ∩ bset A S) ≤ ENNReal.ofReal (x i) * μ (bset A S) :=
    (lll_prob_bset A hA hdg hx₀ hx₁ hLLL S).2 i hi
  calc
    μ[A i | bset A S] = (μ (bset A S))⁻¹ * μ (bset A S ∩ A i) := by
        rw [cond_apply (measurableSet_bset A hA S)]
    _ = (μ (bset A S))⁻¹ * μ (A i ∩ bset A S) := by
        rw [Set.inter_comm]
    _ ≤ (μ (bset A S))⁻¹ * (ENNReal.ofReal (x i) * μ (bset A S)) := by
        exact mul_le_mul_right hP2 (μ (bset A S))⁻¹
    _ = ENNReal.ofReal (x i) := by
        rw [mul_comm (ENNReal.ofReal (x i)) (μ (bset A S)), ← mul_assoc,
          ENNReal.inv_mul_cancel (ne_of_gt hμS₀) (measure_ne_top μ (bset A S)), one_mul]

end TCSLean.LovaszLocal
